const providers=[
{id:1,name:'Generika Drugstore – Quezon City',type:'pharmacy',city:'Quezon City',province:'Metro Manila',address:'102 Tomas Morato Ave, Quezon City',phone:'(02) 8727 0000',lat:14.6339,lng:121.0351,hours:'Open · Closes 9:00 PM'},
{id:2,name:'Mercury Drug – Makati Central',type:'pharmacy',city:'Makati',province:'Metro Manila',address:'Alvarez Bldg, Ayala Ave, Makati',phone:'(02) 8888 9999',lat:14.5547,lng:121.0244,hours:'Open · Closes 10:00 PM'},
{id:3,name:'Southstar Drug – Cebu IT Park',type:'pharmacy',city:'Cebu City',province:'Cebu',address:'Apas, Cebu City, Cebu',phone:'(032) 411 2233',lat:10.329,lng:123.906,hours:'Open · Closes 8:00 PM'},
{id:4,name:'St. Luke’s Medical Center',type:'hospital',city:'Taguig',province:'Metro Manila',address:'32nd Street, Bonifacio Global City',phone:'(02) 8789 7700',lat:14.553,lng:121.048,hours:'Open 24 hours'},
{id:5,name:'Rural Health Unit – Davao',type:'clinic',city:'Davao City',province:'Davao del Sur',address:'J.P. Laurel Ave, Davao City',phone:'(082) 227 1964',lat:7.102,lng:125.613,hours:'Open · Closes 5:00 PM'},
{id:6,name:'TGP Pharmacy – Iloilo',type:'pharmacy',city:'Iloilo City',province:'Iloilo',address:'Ledesma St, Iloilo City',phone:'(033) 320 1840',lat:10.704,lng:122.563,hours:'Open · Closes 9:00 PM'}];
let user=null, active='all', markers={}, selected=null;const map=L.map('map').setView([12.8797,121.774],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
const icon=(color)=>L.divIcon({className:'custom-pin',html:`<div style="width:17px;height:17px;background:${color};border:3px solid white;border-radius:50%;box-shadow:0 2px 6px #123c3555"></div>`,iconSize:[17,17],iconAnchor:[8,8]});
providers.forEach(p=>{markers[p.id]=L.marker([p.lat,p.lng],{icon:icon('#e76f48')}).addTo(map).bindPopup(`<b>${p.name}</b><br><small>${p.address}</small>`).on('click',()=>select(p.id));});
function distance(a,b){const R=6371,d1=(b.lat-a.lat)*Math.PI/180,d2=(b.lng-a.lng)*Math.PI/180;return R*2*Math.asin(Math.sqrt(Math.sin(d1/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(d2/2)**2))}function filtered(){let q=document.querySelector('#search').value.toLowerCase();return providers.filter(p=>(active==='all'||p.type===active)&&(!q||`${p.name} ${p.city} ${p.province}`.toLowerCase().includes(q))).map(p=>({...p,km:user?distance(user,p):null})).sort((a,b)=>(a.km??9999)-(b.km??9999))}
function render(){let list=filtered(),cards=document.querySelector('#cards');cards.innerHTML=list.map(p=>`<article class="card ${selected===p.id?'selected':''}" data-id="${p.id}"><div class="card-top"><div><h3>${p.name}</h3><p>${p.city}, ${p.province}</p></div><span class="badge">${p.type}</span></div><p>⌖ ${p.address}</p><p>◷ ${p.hours}</p>${p.km!==null?`<p class="distance">${p.km<1?(p.km*1000).toFixed(0)+' m':p.km.toFixed(1)+' km'} away</p>`:''}<div class="details"><span>☎ ${p.phone}</span><button class="directions" data-route="${p.id}">Get directions →</button></div></article>`).join('');document.querySelector('#empty').classList.toggle('hidden',!list.length);document.querySelector('#resultCount').textContent=list.length?`${list.length} provider${list.length>1?'s':''} found`:'No providers found';cards.querySelectorAll('.card').forEach(c=>c.onclick=e=>{if(!e.target.matches('.directions'))select(+c.dataset.id)});cards.querySelectorAll('.directions').forEach(b=>b.onclick=e=>{e.stopPropagation();route(+b.dataset.route)});}
function select(id){selected=id;let p=providers.find(x=>x.id===id);map.setView([p.lat,p.lng],14);markers[id].openPopup();document.querySelector('#mapTip').innerHTML=`<b>${p.name}</b><br><span>${p.address}</span>`;render()}async function route(id){let p=providers.find(x=>x.id===id);if(!user){document.querySelector('#locationNotice').textContent='Please allow location access first so we can calculate your route.';document.querySelector('#locationNotice').classList.remove('hidden');return}document.querySelector('#routeTitle').textContent=p.name;document.querySelector('#routeModal').classList.remove('hidden');document.querySelector('#routeSteps').innerHTML='<div class="step">Calculating the best route…</div>';document.querySelector('#openMaps').href=`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`;try{let r=await fetch(`https://router.project-osrm.org/route/v1/driving/${user.lng},${user.lat};${p.lng},${p.lat}?overview=full&steps=true`),d=await r.json(),x=d.routes[0];document.querySelector('#routeDistance').textContent=x.distance<1000?Math.round(x.distance)+' m':(x.distance/1000).toFixed(1)+' km';document.querySelector('#routeTime').textContent=Math.round(x.duration/60)+' min by car';document.querySelector('#routeSteps').innerHTML=x.legs[0].steps.slice(0,12).map(s=>`<div class="step">${s.maneuver.instruction||s.name||'Continue'} <small>· ${(s.distance/1000).toFixed(1)} km</small></div>`).join('')}catch(e){document.querySelector('#routeSteps').innerHTML='<div class="step">Route service unavailable. Use Google Maps for turn-by-turn directions.</div>'}}
function locate(){if(!navigator.geolocation)return alert('Geolocation is not supported by this browser.');navigator.geolocation.getCurrentPosition(pos=>{user={lat:pos.coords.latitude,lng:pos.coords.longitude};L.marker([user.lat,user.lng],{icon:icon('#438bc5')}).addTo(map).bindPopup('You are here').openPopup();map.setView([user.lat,user.lng],12);document.querySelector('#locationNotice').textContent='Location found. Providers are now sorted by distance.';document.querySelector('#locationNotice').classList.remove('hidden');render()},()=>{document.querySelector('#locationNotice').textContent='We could not access your location. Please enable GPS permissions and try again.';document.querySelector('#locationNotice').classList.remove('hidden')})}document.querySelector('#search').oninput=render;document.querySelector('#locate').onclick=locate;document.querySelector('#clear').onclick=()=>{document.querySelector('#search').value='';render()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;render()});document.querySelector('#closeModal').onclick=()=>document.querySelector('#routeModal').classList.add('hidden');document.querySelector('#routeModal').onclick=e=>{if(e.target.id==='routeModal')e.target.classList.add('hidden')};render();
